environment:
  node_pre_gyp_accessKeyId:
    secure: Q/MT3KqteKjl23ePjDY9V93G8Ey91LJAOcvJPdEh0i4=
  node_pre_gyp_secretAccessKey:
    secure: pF+hGI1d/+HVKL0EWCGY6YxvRZrfQrLoxfG5AqQTLJ9hJZaiRRQTwU8cwL+4IEuW

test_script:
  - ps: Install-Product node 0.10 x86
  - .\test\scripts\test
  - ps: Install-Product node 0.10 x64
  - .\test\scripts\test
  - ps: Install-Product node 0.12 x86
  - .\test\scripts\test
  - ps: Install-Product node 0.12 x64
  - .\test\scripts\test
  - ps: Install-Product node 1 x86
  - .\test\scripts\test
  - ps: Install-Product node 1 x64
  - .\test\scripts\test

build: OFF
