# node.js support: Latest stable version, `0.10.x`
# iojs support: Latest stable version
environment:
  node_pre_gyp_accessKeyId:
    secure: Q/MT3KqteKjl23ePjDY9V93G8Ey91LJAOcvJPdEh0i4=
  node_pre_gyp_secretAccessKey:
    secure: pF+hGI1d/+HVKL0EWCGY6YxvRZrfQrLoxfG5AqQTLJ9hJZaiRRQTwU8cwL+4IEuW
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 1.x

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --build-from-source

test_script:
  - node --version
  - npm --version
  - npm test

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules

build: OFF
